name: Publish Release
on:
  release:
    types: [released]
jobs:
  publish:
    name: Publish to Visual Studio Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download release asset
        id: release_asset
        env:
          TAG_NAME: ${{ github.event.tag_name }}
        run: |
          VERSION=$(echo -n $TAG_NAME | sed 's/^v//')
          FILE_NAME="vrealize-developer-tools-${VERSION}.vsix"
          DOWNLOAD_URL=$(jq --raw-output '.release.assets[] | select(.name == "$FILE_NAME") | .browser_download_url' "$GITHUB_EVENT_PATH")

          wget $DOWNLOAD_URL
          echo "::set-output name=file_name::$FILE_NAME"

      - name: Publish
        env:
          MARKETPLACE_SECRET: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          FILE_NAME: ${{ steps.release_asset.outputs.file_name }}
        run: "node node_modules/.bin/vsce publish -p $MARKETPLACE_SECRET --packagePath $FILE_NAME"

  publish-vropkg-ghp:
    name: Publish vropkg to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.14.1"
          registry-url: "https://npm.pkg.github.com"
      - run: |
          yarn
          yarn workspace @vmware-pscoe/vropkg build
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-vrotsc-ghp:
    name: Publish vrotsc to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.14.1"
          registry-url: "https://npm.pkg.github.com"
      - run: |
          yarn
          yarn workspace @vmware-pscoe/vrotsc build
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
